src/Entity/Answers.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AnswersRepository")
 */
class Answers
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $answer_text;

    /**
     * @ORM\Column(type="date")
     */
    private $answer_date;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="answers")
     * @ORM\JoinColumn(nullable=false, name="users_id", referencedColumnName="id")
     */
    private $users;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Questions", inversedBy="answers")
     * @ORM\JoinColumn(nullable=false, name="questions_id", referencedColumnName="id")
     */
    private $questions;

    public function __construct()
    {
        $this->answer_date = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAnswerText(): ?string
    {
        return $this->answer_text;
    }

    public function setAnswerText(string $answer_text): self
    {
        $this->answer_text = $answer_text;

        return $this;
    }

    public function getAnswerDate(): ?\DateTimeInterface
    {
        return $this->answer_date;
    }

    public function setAnswerDate(\DateTimeInterface $answer_date): self
    {
        $this->answer_date = $answer_date;

        return $this;
    }

    public function getUsers(): ?user
    {
        return $this->users;
    }

    public function setUsers(?user $users): self
    {
        $this->users = $users;

        return $this;
    }

    public function getQuestions(): ?questions
    {
        return $this->questions;
    }

    public function setQuestions(?questions $questions): self
    {
        $this->questions = $questions;

        return $this;
    }

    public function __toString()
    {
        return $this->getAnswerText();
    }
}

src/Form/AnswersType.php
<?php

namespace App\Form;

use App\Entity\Answers;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AnswersType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('answer_text')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Answers::class,
        ]);
    }
}

src/Controller/AnswersController.php
<?php

namespace App\Controller;

use App\Entity\Answers;
use App\Form\AnswersType;
use App\Repository\AnswersRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/answers")
 */
class AnswersController extends AbstractController
{
    /**
     * @Route("/", name="answers_index", methods={"GET"})
     */
    public function index(AnswersRepository $answersRepository): Response
    {
        return $this->render('answers/index.html.twig', [
            'answers' => $answersRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="answers_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $answer = new Answers();
        $answer->setUsers($this->getUser());
        $form = $this->createForm(AnswersType::class, $answer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($answer);
            $entityManager->flush();

            return $this->redirectToRoute('answers_index');
        }

        return $this->render('answers/new.html.twig', [
            'answer' => $answer,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="answers_show", methods={"GET"})
     */
    public function show(Answers $answer): Response
    {
        return $this->render('answers/show.html.twig', [
            'answer' => $answer,
        ]);
    }
}

templates/answers/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/answers/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Answers index{% endblock %}

{% block body %}
    <h1>Answers index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Answer_text</th>
                <th>Answer_date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for answer in answers %}
            <tr>
                <td>{{ answer.id }}</td>
                <td>{{ answer.answerText }}</td>
                <td>{{ answer.answerDate ? answer.answerDate|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('answers_show', {'id': answer.id}) }}">show</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('answers_new') }}">Create new</a>
{% endblock %}

templates/answers/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Answers{% endblock %}

{% block body %}
    <h1>Create new Answers</h1>

    {{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
    {{ form_end(form) }}


    <a href="{{ path('answers_index') }}">back to list</a>
{% endblock %}

templates/answers/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Answers{% endblock %}

{% block body %}
    <h1>Answers</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ answer.id }}</td>
            </tr>
            <tr>
                <th>Answer_text</th>
                <td>{{ answer.answerText }}</td>
            </tr>
            <tr>
                <th>Answer_date</th>
                <td>{{ answer.answerDate ? answer.answerDate|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('answers_index') }}">back to list</a>
{% endblock %}